package com.stog.backend.compat;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;

/**
 * Flat JDBC projection. The reconciler folds one-or-more external-reference
 * rows into one {@link CloudPlaceSourceRow} without changing the source.
 */
public record CloudPlaceRow(
    String travelItemId,
    String itemType,
    String name,
    String description,
    Double latitude,
    Double longitude,
    String address,
    String source,
    String sourceItemId,
    String status,
    String environmentType,
    Integer estimatedCost,
    String legacyCellId,
    String legacyH3Index,
    Integer legacyH3Resolution,
    String externalProvider,
    String externalId,
    String rawDigest,
    String licenseDecision,
    List<String> reusableFields,
    JsonNode openingHours,
    JsonNode dateOverrides,
    Boolean crossMidnight,
    Integer visitMinutes,
    String visitMinutesSource,
    Integer visitMinutesOverride,
    JsonNode traits,
    String traitsSource,
    String traitsModel,
    String traitsUpdatedAt,
    String sourceUpdatedAt,
    JsonNode userConstraintArrays,
    Boolean publicCellEligible
) {
    /** Compatibility constructor for the pre-eligibility projection. */
    public CloudPlaceRow(
        String travelItemId,
        String itemType,
        String name,
        String description,
        Double latitude,
        Double longitude,
        String address,
        String source,
        String sourceItemId,
        String status,
        String environmentType,
        Integer estimatedCost,
        String legacyCellId,
        String legacyH3Index,
        Integer legacyH3Resolution,
        String externalProvider,
        String externalId,
        String rawDigest,
        String licenseDecision,
        List<String> reusableFields,
        JsonNode openingHours,
        JsonNode dateOverrides,
        Boolean crossMidnight,
        Integer visitMinutes,
        String visitMinutesSource,
        Integer visitMinutesOverride,
        JsonNode traits,
        String traitsSource,
        String traitsModel,
        String traitsUpdatedAt,
        String sourceUpdatedAt,
        JsonNode userConstraintArrays
    ) {
        this(
            travelItemId,
            itemType,
            name,
            description,
            latitude,
            longitude,
            address,
            source,
            sourceItemId,
            status,
            environmentType,
            estimatedCost,
            legacyCellId,
            legacyH3Index,
            legacyH3Resolution,
            externalProvider,
            externalId,
            rawDigest,
            licenseDecision,
            reusableFields,
            openingHours,
            dateOverrides,
            crossMidnight,
            visitMinutes,
            visitMinutesSource,
            visitMinutesOverride,
            traits,
            traitsSource,
            traitsModel,
            traitsUpdatedAt,
            sourceUpdatedAt,
            userConstraintArrays,
            null
        );
    }

    /** Compatibility constructor for the original place-plus-reference projection. */
    public CloudPlaceRow(
        String travelItemId,
        String itemType,
        String name,
        String description,
        Double latitude,
        Double longitude,
        String address,
        String source,
        String sourceItemId,
        String status,
        String environmentType,
        Integer estimatedCost,
        String legacyCellId,
        String legacyH3Index,
        Integer legacyH3Resolution,
        String externalProvider,
        String externalId
    ) {
        this(
            travelItemId,
            itemType,
            name,
            description,
            latitude,
            longitude,
            address,
            source,
            sourceItemId,
            status,
            environmentType,
            estimatedCost,
            legacyCellId,
            legacyH3Index,
            legacyH3Resolution,
            externalProvider,
            externalId,
            null,
            null,
            List.of(),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }
}
