substitutions:
  _REGION: asia-southeast1
  _REPOSITORY: stog
  _IMAGE: stog-backend
  _IMAGE_TAG: dev

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_IMAGE_TAG}
      - .
  - id: push-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_IMAGE_TAG}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_IMAGE_TAG}
